import type { ComponentType, LazyExoticComponent } from 'react'
import { lazy } from 'react'
import type { LucideIcon } from 'lucide-react'
import {
  ArrowRightLeft,
  PiggyBank,
  Ruler,
  FlipHorizontal2,
  LayoutGrid,
  RefreshCcw,
  FileImage,
  Calculator,
  Image as ImageIcon,
  Palette,
  AudioWaveform,
  Binary,
  Blend,
  BookOpen,
  Box,
  Braces,
  CalendarCheck,
  CalendarClock,
  CaseSensitive,
  ChartColumn,
  Clapperboard,
  ClipboardPaste,
  Clock,
  Contrast,
  Dices,
  Diff,
  Eye,
  FileArchive,
  FileCog,
  FilePen,
  FileSignature,
  FileText,
  FileType,
  Fingerprint,
  Fuel,
  GalleryHorizontal,
  Gauge,
  Globe,
  Hash,
  HeartPulse,
  Images,
  KeyRound,
  Languages,
  Laugh,
  Link,
  MapPin,
  Merge,
  Minimize2,
  Network,
  NotebookPen,
  PenTool,
  Pipette,
  Presentation,
  QrCode,
  ReceiptText,
  Regex,
  ScanText,
  Scissors,
  ScreenShare,
  Settings,
  Sheet,
  Shrink,
  Smile,
  SquareAsterisk,
  SquareDashed,
  Stamp,
  Star,
  SwatchBook,
  Table2,
  TextCursorInput,
  Timer,
  Type,
  WandSparkles,
  Workflow,
} from 'lucide-react'
import type { HandoffKind } from './lib/handoff'

export type ToolCategory =
  'Daily' | 'Image' | 'Document' | 'Data' | 'Media' | 'Developer' | 'Design' | 'Writing' | 'Notes'

/** Display order for navigation and the home page. */
export const CATEGORIES: ToolCategory[] = [
  'Daily',
  'Image',
  'Document',
  'Data',
  'Media',
  'Developer',
  'Design',
  'Writing',
  'Notes',
]

export type CategoryMeta = {
  icon: LucideIcon
  /** CSS custom property holding the category hue, e.g. `var(--cat-image)`. */
  color: string
  blurb: string
}

export const CATEGORY_META: Record<ToolCategory, CategoryMeta> = {
  Daily: { icon: Calculator, color: 'var(--cat-daily)', blurb: 'Calculators, converters, dates, and timers.' },
  Image: { icon: ImageIcon, color: 'var(--cat-image)', blurb: 'Resize, convert, rotate, and edit pictures.' },
  Document: { icon: FileText, color: 'var(--cat-document)', blurb: 'PDF, Word, and Markdown in every direction.' },
  Data: { icon: Sheet, color: 'var(--cat-data)', blurb: 'Spreadsheets, charts, and archives.' },
  Media: { icon: Clapperboard, color: 'var(--cat-media)', blurb: 'Trim, record, and measure audio and video.' },
  Developer: { icon: Braces, color: 'var(--cat-developer)', blurb: 'Formatters, encoders, and generators.' },
  Design: { icon: Palette, color: 'var(--cat-design)', blurb: 'Colour, contrast, gradients, and diagrams.' },
  Writing: { icon: Type, color: 'var(--cat-writing)', blurb: 'Counters, styling, emoji, and speech.' },
  Notes: { icon: NotebookPen, color: 'var(--cat-notes)', blurb: 'Notes, pipelines, and your data.' },
}

export type ToolMeta = {
  id: string
  path: string
  title: string
  blurb: string
  category: ToolCategory
  keywords: string[]
  /** Primary chord shown in the UI, e.g. 'G J' or 'G 4 T'. */
  shortcut?: string
  /** Additional chords that also reach this tool. */
  aliases?: string[]
  accepts?: HandoffKind[]
  /** Glyph shown on cards, the rail, and the tool header. */
  icon: LucideIcon
  /** Flags a tool as recently added on the home page. */
  isNew?: boolean
  component: LazyExoticComponent<ComponentType>
}

export const tools: ToolMeta[] = [
  {
    id: 'convert',
    path: '/convert',
    title: 'Convert',
    blurb: 'Unix time, zones, units, rem/clamp, percent, GST, and split.',
    category: 'Daily',
    icon: ArrowRightLeft,
    keywords: ['unix', 'timezone', 'epoch', 'units', 'px', 'rem', 'clamp', 'percent', 'gst', 'split', 'tip'],
    shortcut: 'G W',
    aliases: ['G 1 C'],
    accepts: ['text'],
    component: lazy(() => import('./tools/convert/ConvertTool')),
  },
  {
    id: 'calculator',
    path: '/calculator',
    title: 'Calculator',
    blurb: 'Scientific calculator you can type into, with memory and history.',
    category: 'Daily',
    icon: Calculator,
    isNew: true,
    keywords: [
      'calculator',
      'calc',
      'scientific',
      'math',
      'sin',
      'cos',
      'log',
      'sqrt',
      'factorial',
      'percent',
      'arithmetic',
    ],
    shortcut: 'G 1 K',
    component: lazy(() => import('./tools/calculator/CalculatorTool')),
  },
  {
    id: 'units',
    path: '/unit-converter',
    title: 'Unit converter',
    blurb: 'Length, weight, temperature, data, pressure, fuel, and 10 more.',
    category: 'Daily',
    icon: Ruler,
    isNew: true,
    keywords: [
      'unit converter',
      'units',
      'cm to inch',
      'kg to lb',
      'celsius',
      'fahrenheit',
      'feet',
      'miles',
      'psi',
      'gb',
      'mpg',
      'area',
      'volume',
      'gaj',
      'tola',
    ],
    shortcut: 'G 1 U',
    component: lazy(() => import('./tools/units/UnitsTool')),
  },
  {
    id: 'finance',
    path: '/finance',
    title: 'Finance calculators',
    blurb: 'Loan EMI, SIP, compound interest, CAGR, and stacked discounts.',
    category: 'Daily',
    icon: PiggyBank,
    isNew: true,
    keywords: [
      'emi',
      'loan',
      'mortgage',
      'sip',
      'mutual fund',
      'compound interest',
      'fd',
      'fixed deposit',
      'cagr',
      'discount',
      'interest',
      'amortization',
    ],
    shortcut: 'G 1 F',
    component: lazy(() => import('./tools/finance/FinanceTool')),
  },
  {
    id: 'links',
    path: '/links',
    title: 'Links & cards',
    blurb: 'WhatsApp, UTM, vCard, and calendar events. No shortener.',
    category: 'Daily',
    icon: Link,
    keywords: ['whatsapp', 'wa.me', 'utm', 'vcard', 'ics', 'calendar', 'campaign'],
    shortcut: 'G O',
    aliases: ['G 1 L'],
    accepts: ['text'],
    component: lazy(() => import('./tools/links/LinksTool')),
  },
  {
    id: 'clipboard',
    path: '/clipboard',
    title: 'Clipboard download',
    blurb: 'Paste an image and save it. No upload hop.',
    category: 'Image',
    icon: ClipboardPaste,
    keywords: ['paste', 'ctrl+v', 'screenshot', 'download', 'clipboard'],
    shortcut: 'G C',
    aliases: ['G 2 C'],
    accepts: ['image'],
    component: lazy(() => import('./tools/clipboard/ClipboardTool')),
  },
  {
    id: 'compress',
    path: '/compress',
    title: 'Resize & compress',
    blurb: 'Hit pixel and kilobyte limits for forms and portals.',
    category: 'Image',
    icon: Minimize2,
    keywords: ['resize', 'compress', 'kb', 'mb', '450', 'government', 'form'],
    shortcut: 'G R',
    aliases: ['G 2 R'],
    accepts: ['image'],
    component: lazy(() => import('./tools/compress/CompressTool')),
  },
  {
    id: 'finish',
    path: '/finish',
    title: 'Image finishing',
    blurb: 'Crop, color, overlay, and export presets. Honest edits only.',
    category: 'Image',
    icon: WandSparkles,
    keywords: ['crop', 'rotate', 'filter', 'overlay', 'marketing', 'export'],
    shortcut: 'G F',
    aliases: ['G 2 I'],
    accepts: ['image'],
    component: lazy(() => import('./tools/finish/FinishTool')),
  },
  {
    id: 'image-convert',
    path: '/image-converter',
    title: 'Image converter',
    blurb: 'JPG, PNG, WebP, AVIF, and BMP in bulk, with optional resizing.',
    category: 'Image',
    icon: RefreshCcw,
    isNew: true,
    keywords: [
      'convert',
      'jpg to png',
      'png to jpg',
      'webp to jpg',
      'webp to png',
      'heic to jpg',
      'avif',
      'bmp',
      'format',
      'batch',
    ],
    shortcut: 'G 2 V',
    accepts: ['image'],
    component: lazy(() => import('./tools/imageConvert/ImageConvertTool')),
  },
  {
    id: 'rotate-flip',
    path: '/rotate-flip',
    title: 'Rotate & flip',
    blurb: 'Turn 90°, mirror left-right or top-bottom, or straighten a tilt.',
    category: 'Image',
    icon: FlipHorizontal2,
    isNew: true,
    keywords: [
      'rotate',
      'flip',
      'mirror',
      'horizontal',
      'vertical',
      'straighten',
      'tilt',
      'turn',
      'upside down',
      'selfie',
    ],
    shortcut: 'G 2 L',
    accepts: ['image'],
    component: lazy(() => import('./tools/rotate/RotateTool')),
  },
  {
    id: 'collage',
    path: '/collage',
    title: 'Image collage',
    blurb: 'Photos in a grid, side by side, or stacked, with spacing and corners.',
    category: 'Image',
    icon: LayoutGrid,
    isNew: true,
    keywords: [
      'collage',
      'combine images',
      'merge images',
      'grid',
      'side by side',
      'stitch',
      'before after',
      'photo strip',
    ],
    shortcut: 'G 2 J',
    accepts: ['image'],
    component: lazy(() => import('./tools/collage/CollageTool')),
  },
  {
    id: 'exif',
    path: '/exif',
    title: 'Image metadata',
    blurb: 'Read EXIF and GPS, then strip tags before you share.',
    category: 'Image',
    icon: MapPin,
    keywords: ['exif', 'gps', 'metadata', 'strip', 'privacy', 'location'],
    shortcut: 'G E',
    aliases: ['G 2 M'],
    accepts: ['image'],
    component: lazy(() => import('./tools/exif/ExifTool')),
  },
  {
    id: 'favicon',
    path: '/favicon',
    title: 'Favicon set',
    blurb: 'One mark to 16–512 PNG icons and a favicon.ico.',
    category: 'Image',
    icon: Star,
    keywords: ['favicon', 'icon', 'apple-touch', 'pwa', 'ico'],
    shortcut: 'G V',
    aliases: ['G 2 F'],
    accepts: ['image'],
    component: lazy(() => import('./tools/favicon/FaviconTool')),
  },
  {
    id: 'passport',
    path: '/passport',
    title: 'Passport sheet',
    blurb: '600×600 cover crop tiled on a 4×6 or A4 print sheet.',
    category: 'Image',
    icon: SquareDashed,
    keywords: ['passport', 'visa', 'photo', 'print', 'id', '600'],
    shortcut: 'G A',
    aliases: ['G 2 P'],
    accepts: ['image'],
    component: lazy(() => import('./tools/passport/PassportTool')),
  },
  {
    id: 'cutout',
    path: '/cutout',
    title: 'Background cutout',
    blurb: 'On-device subject cutout. Photo stays in this tab.',
    category: 'Image',
    icon: Scissors,
    shortcut: 'G 2 B',
    keywords: ['background', 'remove', 'cutout', 'transparent', 'segment', 'selfie'],
    accepts: ['image'],
    component: lazy(() => import('./tools/cutout/CutoutTool')),
  },
  {
    id: 'svg',
    path: '/svg',
    title: 'SVG convert',
    blurb: 'SVG to PNG, or wrap a raster in an honest SVG.',
    category: 'Image',
    icon: PenTool,
    shortcut: 'G 2 S',
    keywords: ['svg', 'png', 'vector', 'raster', 'icon', 'wrap'],
    accepts: ['image'],
    component: lazy(() => import('./tools/svg/SvgTool')),
  },
  {
    id: 'markdown',
    path: '/markdown',
    title: 'Markdown to PDF',
    blurb: 'Preview Markdown, then print or download a PDF.',
    category: 'Document',
    icon: FileText,
    keywords: ['md', 'pdf', 'print', 'document', 'export'],
    shortcut: 'G M',
    aliases: ['G 3 M'],
    accepts: ['text'],
    component: lazy(() => import('./tools/markdown/MarkdownTool')),
  },
  {
    id: 'pdf',
    path: '/pdf',
    title: 'PDF editor',
    blurb: 'Annotate, sign, white-out, and reorder pages offline.',
    category: 'Document',
    icon: FilePen,
    keywords: ['pdf', 'annotate', 'sign', 'signature', 'whiteout', 'reorder', 'rotate', 'edit'],
    shortcut: 'G P',
    aliases: ['G 3 P'],
    accepts: ['pdf'],
    component: lazy(() => import('./tools/pdf/PdfTool')),
  },
  {
    id: 'pages',
    path: '/pages',
    title: 'PDF merge & split',
    blurb: 'Combine PDFs, extract a range, or split to one file per page.',
    category: 'Document',
    icon: Merge,
    keywords: ['merge', 'split', 'extract', 'combine', 'pages', 'zip'],
    shortcut: 'G U',
    aliases: ['G 3 S'],
    accepts: ['pdf'],
    component: lazy(() => import('./tools/pages/PagesTool')),
  },
  {
    id: 'image-pdf',
    path: '/image-pdf',
    title: 'Images to PDF',
    blurb: 'Combine photos and scans into one PDF. Reorder, rotate, set margins.',
    category: 'Document',
    icon: Images,
    keywords: [
      'image to pdf',
      'jpg to pdf',
      'jpeg to pdf',
      'png to pdf',
      'photo to pdf',
      'images',
      'combine',
      'scan',
      'packet',
      'reorder',
      'convert',
    ],
    shortcut: 'G I',
    aliases: ['G 3 I'],
    accepts: ['image'],
    component: lazy(() => import('./tools/imagePdf/ImagePdfTool')),
  },
  {
    id: 'pdf-images',
    path: '/pdf-to-images',
    title: 'PDF to images',
    blurb: 'Every page, or just the ones you pick, as PNG, JPEG, or WebP.',
    category: 'Document',
    icon: FileImage,
    isNew: true,
    keywords: [
      'pdf to jpg',
      'pdf to png',
      'pdf to image',
      'pdf to jpeg',
      'webp',
      'extract pages',
      'rasterize',
      'dpi',
      'convert',
    ],
    shortcut: 'G 3 J',
    accepts: ['pdf'],
    component: lazy(() => import('./tools/pdfImages/PdfImagesTool')),
  },
  {
    id: 'ocr',
    path: '/ocr',
    title: 'OCR',
    blurb: 'Read printed text from a photo. Image never leaves the tab.',
    category: 'Document',
    icon: ScanText,
    keywords: ['ocr', 'tesseract', 'scan', 'text', 'screenshot', 'read'],
    shortcut: 'G Z',
    aliases: ['G 3 O'],
    accepts: ['image'],
    component: lazy(() => import('./tools/ocr/OcrTool')),
  },
  {
    id: 'forms',
    path: '/forms',
    title: 'PDF form fill',
    blurb: 'Fill AcroForm fields offline, then download.',
    category: 'Document',
    icon: FileSignature,
    shortcut: 'G 3 F',
    keywords: ['form', 'acroform', 'fill', 'pdf', 'fields'],
    accepts: ['pdf'],
    component: lazy(() => import('./tools/forms/FormsTool')),
  },
  {
    id: 'office',
    path: '/office',
    title: 'Office to PDF',
    blurb: 'Word, PowerPoint, Excel, or Markdown into a PDF or .docx.',
    category: 'Document',
    icon: Presentation,
    shortcut: 'G 3 W',
    keywords: [
      'word to pdf',
      'word',
      'docx',
      'doc',
      'pptx',
      'powerpoint',
      'slides',
      'excel',
      'xlsx',
      'rtf',
      'office',
      'convert',
      'pdf',
      'html',
    ],
    accepts: ['text'],
    component: lazy(() => import('./tools/office/OfficeTool')),
  },
  {
    id: 'pdf-text',
    path: '/pdf-text',
    title: 'PDF to Word & text',
    blurb: 'Lift the text out of a PDF as .docx, Markdown, or plain text.',
    category: 'Document',
    icon: FileType,
    shortcut: 'G 3 X',
    keywords: ['pdf to word', 'docx', 'extract', 'text', 'copy out', 'convert', 'markdown', 'retype'],
    accepts: ['pdf'],
    component: lazy(() => import('./tools/pdftext/PdfTextTool')),
  },
  {
    id: 'stamp',
    path: '/stamp',
    title: 'Watermark & page numbers',
    blurb: 'Stamp a watermark, page numbers, Bates numbers, or a running head.',
    category: 'Document',
    icon: Stamp,
    shortcut: 'G 3 K',
    keywords: [
      'watermark',
      'page number',
      'bates',
      'stamp',
      'header',
      'footer',
      'draft',
      'confidential',
      'rotate',
      'remove pages',
    ],
    accepts: ['pdf'],
    component: lazy(() => import('./tools/stamp/StampTool')),
  },
  {
    id: 'json',
    path: '/json',
    title: 'JSON formatter',
    blurb: 'Format, validate, and minify with exact error lines.',
    category: 'Developer',
    icon: Braces,
    keywords: ['json', 'format', 'validate', 'minify', 'pretty', 'parse', 'lint', 'escape'],
    shortcut: 'G J',
    aliases: ['G 6 J'],
    accepts: ['text'],
    component: lazy(() => import('./tools/json/JsonTool')),
  },
  {
    id: 'diff',
    path: '/diff',
    title: 'Text diff',
    blurb: 'Line-by-line compare, with optional JSON pretty-print.',
    category: 'Developer',
    icon: Diff,
    keywords: ['diff', 'compare', 'patch', 'unified', 'text', 'json'],
    shortcut: 'G X',
    aliases: ['G 6 T'],
    accepts: ['text'],
    component: lazy(() => import('./tools/diff/DiffTool')),
  },
  {
    id: 'password',
    path: '/password',
    title: 'Password generator',
    blurb: 'Secure passwords, API tokens, and PINs with strength scoring.',
    category: 'Developer',
    icon: KeyRound,
    keywords: ['password', 'token', 'secret', 'uuid', 'hex', 'entropy', 'secure', 'random', 'pin'],
    shortcut: 'G S',
    aliases: ['G 6 P'],
    component: lazy(() => import('./tools/password/PasswordTool')),
  },
  {
    id: 'qr',
    path: '/qr',
    title: 'QR code',
    blurb: 'Generate or scan links, Wi-Fi, email, or SMS as QR codes.',
    category: 'Developer',
    icon: QrCode,
    keywords: ['qr', 'qrcode', 'wifi', 'link', 'scan', 'svg', 'barcode', 'camera'],
    shortcut: 'G Q',
    aliases: ['G 6 Q'],
    accepts: ['image', 'text'],
    component: lazy(() => import('./tools/qr/QrTool')),
  },
  {
    id: 'encode',
    path: '/encode',
    title: 'Encode',
    blurb: 'Base64, URL, JWT inspect, and SHA hashes. Local only.',
    category: 'Developer',
    icon: Binary,
    keywords: ['base64', 'url', 'jwt', 'sha', 'hash', 'encode', 'decode', 'token'],
    shortcut: 'G B',
    aliases: ['G 6 E'],
    accepts: ['text'],
    component: lazy(() => import('./tools/encode/EncodeTool')),
  },
  {
    id: 'text',
    path: '/text',
    title: 'Text bench',
    blurb: 'Case, slugs, word count, CSV ↔ JSON, and dummy copy.',
    category: 'Developer',
    icon: CaseSensitive,
    keywords: ['case', 'slug', 'word count', 'csv', 'json', 'lorem', 'dummy'],
    shortcut: 'G L',
    aliases: ['G 6 B'],
    accepts: ['text'],
    component: lazy(() => import('./tools/text/TextTool')),
  },
  {
    id: 'regex',
    path: '/regex',
    title: 'Regex tester',
    blurb: 'Match, groups, and replace with this browser’s RegExp.',
    category: 'Developer',
    icon: Regex,
    keywords: ['regex', 'regexp', 'match', 'replace', 'groups', 'pattern'],
    shortcut: 'G Y',
    aliases: ['G 6 R'],
    accepts: ['text'],
    component: lazy(() => import('./tools/regex/RegexTool')),
  },
  {
    id: 'gradient',
    path: '/gradient',
    title: 'Gradient builder',
    blurb: 'Linear, radial, conic, and mesh gradients as CSS or SVG.',
    category: 'Design',
    icon: Blend,
    keywords: ['gradient', 'css', 'svg', 'linear', 'radial', 'conic', 'mesh', 'color', 'background'],
    shortcut: 'G D',
    aliases: ['G 7 G'],
    component: lazy(() => import('./tools/gradient/GradientTool')),
  },
  {
    id: 'tailwind',
    path: '/tailwind',
    title: 'Tailwind theme builder',
    blurb: 'OKLCH color scales and tokens as Tailwind v4 @theme blocks.',
    category: 'Design',
    icon: SwatchBook,
    keywords: ['tailwind', 'theme', 'oklch', 'palette', 'scale', 'tokens', 'css', 'v4', 'design system'],
    shortcut: 'G T',
    aliases: ['G 7 T'],
    component: lazy(() => import('./tools/tailwind/TailwindTool')),
  },
  {
    id: 'contrast',
    path: '/contrast',
    title: 'Contrast checker',
    blurb: 'WCAG contrast with eyedropper or a sampled screenshot.',
    category: 'Design',
    icon: Contrast,
    keywords: ['contrast', 'wcag', 'aa', 'aaa', 'accessibility', 'eyedropper', 'color'],
    shortcut: 'G K',
    aliases: ['G 7 C'],
    accepts: ['image'],
    component: lazy(() => import('./tools/contrast/ContrastTool')),
  },
  {
    id: 'picker',
    path: '/picker',
    title: 'Color picker',
    blurb: 'Sample a pixel. Copy hex, RGB, HSL, or OKLCH.',
    category: 'Design',
    icon: Pipette,
    shortcut: 'G 7 P',
    keywords: ['color', 'picker', 'eyedropper', 'hex', 'oklch', 'hsl', 'sample'],
    accepts: ['image'],
    component: lazy(() => import('./tools/picker/PickerTool')),
  },
  {
    id: 'shrink',
    path: '/shrink',
    title: 'PDF shrink',
    blurb: 'Re-render a scan or export to land under an upload limit.',
    category: 'Document',
    icon: Shrink,
    shortcut: 'G 3 D',
    keywords: ['pdf', 'compress', 'shrink', 'smaller', 'size', 'scan', 'upload', 'limit', 'mb', 'reduce'],
    accepts: ['pdf'],
    component: lazy(() => import('./tools/shrink/ShrinkTool')),
  },
  {
    id: 'mdtable',
    path: '/mdtable',
    title: 'Markdown table',
    blurb: 'Edit tables in a grid, not by counting pipes.',
    category: 'Document',
    icon: Table2,
    shortcut: 'G 3 T',
    keywords: ['markdown', 'table', 'pipe', 'grid', 'md', 'readme', 'align'],
    accepts: ['text'],
    component: lazy(() => import('./tools/mdtable/MdTableTool')),
  },
  {
    id: 'invoice',
    path: '/invoice',
    title: 'Invoice',
    blurb: 'Line items and tax to a clean PDF. Draft stays local.',
    category: 'Document',
    icon: ReceiptText,
    shortcut: 'G 3 N',
    keywords: ['invoice', 'bill', 'receipt', 'gst', 'tax', 'freelance', 'pdf', 'quote'],
    component: lazy(() => import('./tools/invoice/InvoiceTool')),
  },
  {
    id: 'table',
    path: '/table',
    title: 'Data table',
    blurb: 'Open CSV, JSON, or .xlsx. Sort, clean, and export.',
    category: 'Data',
    icon: Sheet,
    shortcut: 'G 4 D',
    keywords: ['csv', 'tsv', 'excel', 'xlsx', 'spreadsheet', 'table', 'sort', 'filter', 'dedupe', 'clean', 'data'],
    accepts: ['text'],
    component: lazy(() => import('./tools/table/TableTool')),
  },
  {
    id: 'chart',
    path: '/chart',
    title: 'Chart maker',
    blurb: 'CSV to bar, line, area, scatter, or pie — as SVG or PNG.',
    category: 'Data',
    icon: ChartColumn,
    shortcut: 'G 4 C',
    keywords: ['chart', 'graph', 'plot', 'bar', 'line', 'pie', 'donut', 'scatter', 'visualise', 'csv', 'svg'],
    accepts: ['text'],
    component: lazy(() => import('./tools/chart/ChartTool')),
  },
  {
    id: 'archive',
    path: '/archive',
    title: 'ZIP archive',
    blurb: 'Bundle files into one .zip, or open one and pull files back out.',
    category: 'Data',
    icon: FileArchive,
    shortcut: 'G 4 Z',
    keywords: ['zip', 'archive', 'bundle', 'extract', 'unzip', 'attach', 'package', 'folder'],
    accepts: ['image', 'pdf', 'text'],
    component: lazy(() => import('./tools/archive/ArchiveTool')),
  },
  {
    id: 'media',
    path: '/media',
    title: 'Video & audio trim',
    blurb: 'Cut a clip, shrink it for upload, or pull the audio out.',
    category: 'Media',
    icon: Clapperboard,
    shortcut: 'G 5 V',
    keywords: ['video', 'audio', 'trim', 'cut', 'clip', 'compress', 'mp4', 'webm', 'extract', 'mute', 'shrink'],
    component: lazy(() => import('./tools/media/MediaTool')),
  },
  {
    id: 'record',
    path: '/record',
    title: 'Screen & camera recorder',
    blurb: 'Record the screen, camera, or mic and save the file.',
    category: 'Media',
    icon: ScreenShare,
    shortcut: 'G 5 S',
    keywords: ['record', 'screen', 'capture', 'webcam', 'camera', 'microphone', 'demo', 'video', 'voice'],
    component: lazy(() => import('./tools/record/RecordTool')),
  },
  {
    id: 'checksum',
    path: '/checksum',
    title: 'Checksum',
    blurb: 'SHA and CRC digests for any file, with match checking.',
    category: 'Developer',
    icon: Fingerprint,
    shortcut: 'G 6 C',
    keywords: ['hash', 'checksum', 'sha256', 'sha1', 'sha512', 'crc32', 'verify', 'digest', 'fingerprint', 'integrity'],
    component: lazy(() => import('./tools/checksum/ChecksumTool')),
  },
  {
    id: 'config',
    path: '/config',
    title: 'JSON · YAML · TOML',
    blurb: 'Convert between the three config formats.',
    category: 'Developer',
    icon: FileCog,
    shortcut: 'G 6 Y',
    keywords: ['yaml', 'yml', 'toml', 'json', 'convert', 'config', 'settings', 'front matter'],
    accepts: ['text'],
    component: lazy(() => import('./tools/config/ConfigTool')),
  },
  {
    id: 'cron',
    path: '/cron',
    title: 'Cron builder',
    blurb: 'Read a schedule in English and preview the next runs.',
    category: 'Developer',
    icon: CalendarClock,
    shortcut: 'G 6 O',
    keywords: ['cron', 'crontab', 'schedule', 'job', 'timer', 'expression', 'quartz'],
    accepts: ['text'],
    component: lazy(() => import('./tools/cron/CronTool')),
  },
  {
    id: 'base',
    path: '/base',
    title: 'Number base',
    blurb: 'Binary, octal, hex, and bitwise with a bit inspector.',
    category: 'Developer',
    icon: Hash,
    shortcut: 'G 6 N',
    keywords: ['binary', 'hex', 'octal', 'decimal', 'bitwise', 'bit', 'mask', 'shift', 'two complement', 'radix'],
    accepts: ['text'],
    component: lazy(() => import('./tools/base/BaseTool')),
  },
  {
    id: 'diagram',
    path: '/diagram',
    title: 'Diagram',
    blurb: 'Mermaid flowcharts and sequences as SVG or PNG.',
    category: 'Design',
    icon: Network,
    shortcut: 'G 7 D',
    keywords: ['mermaid', 'diagram', 'flowchart', 'sequence', 'gantt', 'graph', 'architecture', 'svg'],
    accepts: ['text'],
    component: lazy(() => import('./tools/diagram/DiagramTool')),
  },
  {
    id: 'vision',
    path: '/vision',
    title: 'Colour vision',
    blurb: 'Simulate colour blindness on a palette or screenshot.',
    category: 'Design',
    icon: Eye,
    shortcut: 'G 7 V',
    keywords: [
      'colour blind',
      'color blind',
      'deuteranopia',
      'protanopia',
      'tritanopia',
      'accessibility',
      'a11y',
      'palette',
      'simulate',
    ],
    accepts: ['image'],
    component: lazy(() => import('./tools/vision/VisionTool')),
  },
  {
    id: 'meet',
    path: '/meet',
    title: 'Meeting planner',
    blurb: 'Line up working hours across zones and find the overlap.',
    category: 'Daily',
    icon: Globe,
    shortcut: 'G 1 M',
    keywords: ['meeting', 'timezone', 'time zone', 'overlap', 'schedule', 'world clock', 'standup', 'call'],
    component: lazy(() => import('./tools/meet/MeetTool')),
  },
  {
    id: 'age',
    path: '/age',
    title: 'Age & date difference',
    blurb: 'Exact years, months, and days between two dates.',
    category: 'Daily',
    icon: Clock,
    shortcut: 'G 1 A',
    keywords: ['age', 'date', 'difference', 'birthday', 'anniversary', 'days between', 'how old'],
    accepts: ['text'],
    component: lazy(() => import('./tools/age/AgeTool')),
  },
  {
    id: 'deadline',
    path: '/deadline',
    title: 'Deadline calculator',
    blurb: 'Add working days, skipping weekends and your holidays.',
    category: 'Daily',
    icon: CalendarCheck,
    shortcut: 'G 1 D',
    keywords: ['deadline', 'working days', 'business days', 'sla', 'due date', 'holidays', 'turnaround'],
    accepts: ['text'],
    component: lazy(() => import('./tools/deadline/DeadlineTool')),
  },
  {
    id: 'timers',
    path: '/timers',
    title: 'Timers',
    blurb: 'Countdown, stopwatch, and Pomodoro in one place.',
    category: 'Daily',
    icon: Timer,
    shortcut: 'G 1 T',
    keywords: ['timer', 'countdown', 'stopwatch', 'pomodoro', 'alarm', 'focus', 'lap'],
    component: lazy(() => import('./tools/timers/TimersTool')),
  },
  {
    id: 'random',
    path: '/random',
    title: 'Random picker',
    blurb: 'Wheel spinner, dice, coin flip, and fair team splitting.',
    category: 'Daily',
    icon: Dices,
    shortcut: 'G 1 R',
    keywords: ['random', 'wheel', 'spinner', 'dice', 'coin', 'teams', 'raffle', 'shuffle', 'pick'],
    accepts: ['text'],
    component: lazy(() => import('./tools/random/RandomTool')),
  },
  {
    id: 'numwords',
    path: '/numwords',
    title: 'Number to words',
    blurb: 'Spell out amounts in lakh, crore, or millions.',
    category: 'Daily',
    icon: Languages,
    shortcut: 'G 1 N',
    keywords: ['number to words', 'amount in words', 'cheque', 'lakh', 'crore', 'rupees', 'spell', 'invoice'],
    accepts: ['text'],
    component: lazy(() => import('./tools/numwords/NumWordsTool')),
  },
  {
    id: 'health',
    path: '/health',
    title: 'Health calculators',
    blurb: 'BMI, resting energy, daily calories, and macros.',
    category: 'Daily',
    icon: HeartPulse,
    shortcut: 'G 1 H',
    keywords: ['bmi', 'bmr', 'tdee', 'calories', 'macros', 'protein', 'weight', 'fitness', 'diet'],
    component: lazy(() => import('./tools/health/HealthTool')),
  },
  {
    id: 'trip',
    path: '/trip',
    title: 'Trip cost',
    blurb: 'Fuel, tolls, and per-head split for a journey.',
    category: 'Daily',
    icon: Fuel,
    shortcut: 'G 1 I',
    keywords: ['fuel', 'petrol', 'mileage', 'trip', 'travel', 'split', 'road trip', 'toll', 'cost'],
    component: lazy(() => import('./tools/trip/TripTool')),
  },
  {
    id: 'carousel',
    path: '/carousel',
    title: 'Carousel splitter',
    blurb: 'Slice a wide image into numbered Instagram panels.',
    category: 'Image',
    icon: GalleryHorizontal,
    shortcut: 'G 2 A',
    keywords: ['carousel', 'instagram', 'slice', 'split', 'panels', 'swipe', 'linkedin', 'panorama'],
    accepts: ['image'],
    component: lazy(() => import('./tools/carousel/CarouselTool')),
  },
  {
    id: 'meme',
    path: '/meme',
    title: 'Meme generator',
    blurb: 'Top and bottom text with the right stroke and font.',
    category: 'Image',
    icon: Laugh,
    shortcut: 'G 2 G',
    keywords: ['meme', 'caption', 'impact', 'top text', 'bottom text', 'funny'],
    accepts: ['image'],
    component: lazy(() => import('./tools/meme/MemeTool')),
  },
  {
    id: 'ascii',
    path: '/ascii',
    title: 'ASCII from image',
    blurb: 'Turn a photo into text art at any density.',
    category: 'Image',
    icon: SquareAsterisk,
    shortcut: 'G 2 O',
    keywords: ['ascii', 'art', 'text art', 'image to text', 'terminal', 'retro'],
    accepts: ['image'],
    component: lazy(() => import('./tools/ascii/AsciiTool')),
  },
  {
    id: 'noise',
    path: '/noise',
    title: 'Noise generator',
    blurb: 'White, pink, and brown noise with a sleep timer.',
    category: 'Media',
    icon: AudioWaveform,
    shortcut: 'G 5 N',
    keywords: ['noise', 'white noise', 'pink', 'brown', 'sleep', 'focus', 'ambient', 'concentration'],
    component: lazy(() => import('./tools/noise/NoiseTool')),
  },
  {
    id: 'soundmeter',
    path: '/soundmeter',
    title: 'Sound meter',
    blurb: 'Live decibel reading from the microphone.',
    category: 'Media',
    icon: Gauge,
    shortcut: 'G 5 M',
    keywords: ['decibel', 'db', 'sound', 'loudness', 'noise level', 'spl', 'microphone', 'meter'],
    component: lazy(() => import('./tools/soundmeter/SoundMeterTool')),
  },
  {
    id: 'styler',
    path: '/styler',
    title: 'Unicode text styler',
    blurb: 'Bold and italic for bios that strip formatting.',
    category: 'Writing',
    icon: Type,
    shortcut: 'G 8 U',
    keywords: ['unicode', 'bold', 'italic', 'fancy text', 'bio', 'font', 'style', 'instagram', 'twitter'],
    accepts: ['text'],
    component: lazy(() => import('./tools/styler/StylerTool')),
  },
  {
    id: 'emoji',
    path: '/emoji',
    title: 'Emoji search',
    blurb: 'Find emoji and kaomoji by meaning, copy instantly.',
    category: 'Writing',
    icon: Smile,
    shortcut: 'G 8 E',
    keywords: ['emoji', 'emoticon', 'kaomoji', 'smiley', 'symbol', 'search', 'copy'],
    component: lazy(() => import('./tools/emoji/EmojiTool')),
  },
  {
    id: 'counter',
    path: '/counter',
    title: 'Platform counter',
    blurb: 'Character counts against X, LinkedIn, and SEO limits.',
    category: 'Writing',
    icon: TextCursorInput,
    shortcut: 'G 8 P',
    keywords: ['character count', 'word count', 'limit', 'twitter', 'x', 'linkedin', 'meta description', 'seo', 'sms'],
    accepts: ['text'],
    component: lazy(() => import('./tools/counter/CounterTool')),
  },
  {
    id: 'readability',
    path: '/readability',
    title: 'Readability',
    blurb: 'Reading time, Flesch score, and the sentences to fix.',
    category: 'Writing',
    icon: BookOpen,
    shortcut: 'G 8 R',
    keywords: ['readability', 'flesch', 'reading time', 'grade level', 'passive voice', 'editing', 'clarity'],
    accepts: ['text'],
    component: lazy(() => import('./tools/readability/ReadabilityTool')),
  },
  {
    id: 'boxdraw',
    path: '/boxdraw',
    title: 'Box drawing',
    blurb: 'ASCII tables, boxes, and trees for READMEs.',
    category: 'Writing',
    icon: Box,
    shortcut: 'G 8 B',
    keywords: ['ascii table', 'box drawing', 'tree', 'readme', 'unicode', 'terminal', 'comment', 'diagram'],
    accepts: ['text'],
    component: lazy(() => import('./tools/boxdraw/BoxDrawTool')),
  },
  {
    id: 'settings',
    path: '/settings',
    title: 'Data & settings',
    blurb: 'Back up everything, restore it, and see what you use most.',
    category: 'Notes',
    icon: Settings,
    shortcut: 'G 9 D',
    keywords: ['backup', 'restore', 'export', 'import', 'settings', 'data', 'storage', 'clear', 'usage'],
    component: lazy(() => import('./tools/settings/SettingsTool')),
  },
  {
    id: 'pipelines',
    path: '/pipelines',
    title: 'Pipelines',
    blurb: 'Save a sequence of tools and rerun it on demand.',
    category: 'Notes',
    icon: Workflow,
    shortcut: 'G 9 P',
    keywords: ['pipeline', 'workflow', 'chain', 'recipe', 'automation', 'steps', 'batch', 'repeat'],
    component: lazy(() => import('./tools/pipelines/PipelinesTool')),
  },
  {
    id: 'notes',
    path: '/notes',
    title: 'Local notes',
    blurb: 'A scratchpad that stays in this browser.',
    category: 'Notes',
    icon: NotebookPen,
    keywords: ['note', 'scratch', 'localstorage', 'indexeddb', 'memo'],
    shortcut: 'G N',
    aliases: ['G 9 L'],
    accepts: ['text'],
    component: lazy(() => import('./tools/notes/NotesTool')),
  },
]

/** Words that carry no meaning in a search like "convert pdf to jpg". */
const STOP_WORDS = new Set(['to', 'a', 'an', 'the', 'and', 'or', 'of', 'for', 'into', 'in', 'my', 'from', 'with'])

function tokens(value: string): string[] {
  return value
    .toLowerCase()
    .split(/[^\p{L}\p{N}.+#]+/u)
    .filter((word) => word && !STOP_WORDS.has(word))
}

/**
 * Scores how well a tool answers a query; 0 means it does not match.
 *
 * Every meaningful word must appear somewhere, so "pdf to jpg" finds the PDF
 * to images tool without that exact phrase being a keyword. Where the words
 * land decides the rank: a title hit beats a keyword, which beats the blurb.
 */
export function scoreTool(tool: ToolMeta, query: string): number {
  const q = query.trim().toLowerCase()
  if (!q) return 1
  const title = tool.title.toLowerCase()
  const keywords = tool.keywords.map((k) => k.toLowerCase())
  const hay = [title, tool.blurb.toLowerCase(), tool.category.toLowerCase(), ...keywords].join(' ')

  let score = 0
  if (title === q) score += 120
  else if (title.startsWith(q)) score += 80
  else if (title.includes(q)) score += 50
  if (keywords.includes(q)) score += 45
  else if (keywords.some((k) => k.includes(q))) score += 25
  if (hay.includes(q)) score += 10

  const words = tokens(q)
  if (!words.length) return score
  for (const word of words) {
    if (!hay.includes(word)) return score >= 10 ? score : 0
    if (title.includes(word)) score += 8
    else if (keywords.some((k) => k.includes(word))) score += 5
    else score += 2
  }
  return score
}

export function searchTools(query: string): ToolMeta[] {
  if (!query.trim()) return tools
  return tools
    .map((tool, index) => ({ tool, index, score: scoreTool(tool, query) }))
    .filter((row) => row.score > 0)
    .sort((a, b) => b.score - a.score || a.index - b.index)
    .map((row) => row.tool)
}

export function getTool(id: string): ToolMeta | undefined {
  return tools.find((tool) => tool.id === id)
}

export function toolForPath(pathname: string): ToolMeta | undefined {
  const clean = pathname.length > 1 ? pathname.replace(/\/+$/, '') : pathname
  return tools.find((tool) => tool.path === clean)
}

/** Pinned count. Sitemap/OG are generated from `tools`; chrome copy and tests must match this. */
export const TOOL_COUNT = 72
