import type { ComponentType, LazyExoticComponent } from 'react'
import { lazy } from 'react'
import type { HandoffKind } from './lib/handoff'

export type ToolCategory =
  | 'Daily'
  | 'Image'
  | 'Document'
  | 'Data'
  | 'Media'
  | 'Developer'
  | 'Design'
  | 'Writing'
  | 'Notes'

/** Display order for navigation and the home page. */
export const CATEGORIES: ToolCategory[] = [
  'Daily',
  'Image',
  'Document',
  'Data',
  'Media',
  'Developer',
  'Design',
  'Writing',
  'Notes',
]

export type ToolMeta = {
  id: string
  path: string
  title: string
  blurb: string
  category: ToolCategory
  keywords: string[]
  /** Primary chord shown in the UI, e.g. 'G J' or 'G 4 T'. */
  shortcut?: string
  /** Additional chords that also reach this tool. */
  aliases?: string[]
  accepts?: HandoffKind[]
  component: LazyExoticComponent<ComponentType>
}

export const tools: ToolMeta[] = [
  {
    id: 'convert',
    path: '/convert',
    title: 'Convert',
    blurb: 'Unix time, zones, units, rem/clamp, percent, GST, and split.',
    category: 'Daily',
    keywords: ['unix', 'timezone', 'epoch', 'units', 'px', 'rem', 'clamp', 'percent', 'gst', 'split', 'tip'],
    shortcut: 'G W',
    aliases: ['G 1 C'],
    accepts: ['text'],
    component: lazy(() => import('./tools/convert/ConvertTool')),
  },
  {
    id: 'links',
    path: '/links',
    title: 'Links & cards',
    blurb: 'WhatsApp, UTM, vCard, and calendar events. No shortener.',
    category: 'Daily',
    keywords: ['whatsapp', 'wa.me', 'utm', 'vcard', 'ics', 'calendar', 'campaign'],
    shortcut: 'G O',
    aliases: ['G 1 L'],
    accepts: ['text'],
    component: lazy(() => import('./tools/links/LinksTool')),
  },
  {
    id: 'clipboard',
    path: '/clipboard',
    title: 'Clipboard download',
    blurb: 'Paste an image and save it. No upload hop.',
    category: 'Image',
    keywords: ['paste', 'ctrl+v', 'screenshot', 'download', 'clipboard'],
    shortcut: 'G C',
    aliases: ['G 2 C'],
    accepts: ['image'],
    component: lazy(() => import('./tools/clipboard/ClipboardTool')),
  },
  {
    id: 'compress',
    path: '/compress',
    title: 'Resize & compress',
    blurb: 'Hit pixel and kilobyte limits for forms and portals.',
    category: 'Image',
    keywords: ['resize', 'compress', 'kb', 'mb', '450', 'government', 'form'],
    shortcut: 'G R',
    aliases: ['G 2 R'],
    accepts: ['image'],
    component: lazy(() => import('./tools/compress/CompressTool')),
  },
  {
    id: 'finish',
    path: '/finish',
    title: 'Image finishing',
    blurb: 'Crop, color, overlay, and export presets. Honest edits only.',
    category: 'Image',
    keywords: ['crop', 'rotate', 'filter', 'overlay', 'marketing', 'export'],
    shortcut: 'G F',
    aliases: ['G 2 I'],
    accepts: ['image'],
    component: lazy(() => import('./tools/finish/FinishTool')),
  },
  {
    id: 'exif',
    path: '/exif',
    title: 'Image metadata',
    blurb: 'Read EXIF and GPS, then strip tags before you share.',
    category: 'Image',
    keywords: ['exif', 'gps', 'metadata', 'strip', 'privacy', 'location'],
    shortcut: 'G E',
    aliases: ['G 2 M'],
    accepts: ['image'],
    component: lazy(() => import('./tools/exif/ExifTool')),
  },
  {
    id: 'favicon',
    path: '/favicon',
    title: 'Favicon set',
    blurb: 'One mark to 16–512 PNG icons and a favicon.ico.',
    category: 'Image',
    keywords: ['favicon', 'icon', 'apple-touch', 'pwa', 'ico'],
    shortcut: 'G V',
    aliases: ['G 2 F'],
    accepts: ['image'],
    component: lazy(() => import('./tools/favicon/FaviconTool')),
  },
  {
    id: 'passport',
    path: '/passport',
    title: 'Passport sheet',
    blurb: '600×600 cover crop tiled on a 4×6 or A4 print sheet.',
    category: 'Image',
    keywords: ['passport', 'visa', 'photo', 'print', 'id', '600'],
    shortcut: 'G A',
    aliases: ['G 2 P'],
    accepts: ['image'],
    component: lazy(() => import('./tools/passport/PassportTool')),
  },
  {
    id: 'cutout',
    path: '/cutout',
    title: 'Background cutout',
    blurb: 'On-device subject cutout. Photo stays in this tab.',
    category: 'Image',
    shortcut: 'G 2 B',
    keywords: ['background', 'remove', 'cutout', 'transparent', 'segment', 'selfie'],
    accepts: ['image'],
    component: lazy(() => import('./tools/cutout/CutoutTool')),
  },
  {
    id: 'svg',
    path: '/svg',
    title: 'SVG convert',
    blurb: 'SVG to PNG, or wrap a raster in an honest SVG.',
    category: 'Image',
    shortcut: 'G 2 S',
    keywords: ['svg', 'png', 'vector', 'raster', 'icon', 'wrap'],
    accepts: ['image'],
    component: lazy(() => import('./tools/svg/SvgTool')),
  },
  {
    id: 'markdown',
    path: '/markdown',
    title: 'Markdown to PDF',
    blurb: 'Preview Markdown, then print or download a PDF.',
    category: 'Document',
    keywords: ['md', 'pdf', 'print', 'document', 'export'],
    shortcut: 'G M',
    aliases: ['G 3 M'],
    accepts: ['text'],
    component: lazy(() => import('./tools/markdown/MarkdownTool')),
  },
  {
    id: 'pdf',
    path: '/pdf',
    title: 'PDF editor',
    blurb: 'Annotate, sign, white-out, and reorder pages offline.',
    category: 'Document',
    keywords: ['pdf', 'annotate', 'sign', 'signature', 'whiteout', 'reorder', 'rotate', 'edit'],
    shortcut: 'G P',
    aliases: ['G 3 P'],
    accepts: ['pdf'],
    component: lazy(() => import('./tools/pdf/PdfTool')),
  },
  {
    id: 'pages',
    path: '/pages',
    title: 'PDF merge & split',
    blurb: 'Combine PDFs, extract a range, or split to one file per page.',
    category: 'Document',
    keywords: ['merge', 'split', 'extract', 'combine', 'pages', 'zip'],
    shortcut: 'G U',
    aliases: ['G 3 S'],
    accepts: ['pdf'],
    component: lazy(() => import('./tools/pages/PagesTool')),
  },
  {
    id: 'image-pdf',
    path: '/image-pdf',
    title: 'Image ↔ PDF',
    blurb: 'Screenshots into a packet, or PDF pages out as JPEGs.',
    category: 'Document',
    keywords: ['image', 'pdf', 'scan', 'jpeg', 'convert', 'packet'],
    shortcut: 'G I',
    aliases: ['G 3 I'],
    accepts: ['image', 'pdf'],
    component: lazy(() => import('./tools/imagePdf/ImagePdfTool')),
  },
  {
    id: 'ocr',
    path: '/ocr',
    title: 'OCR',
    blurb: 'Read printed text from a photo. Image never leaves the tab.',
    category: 'Document',
    keywords: ['ocr', 'tesseract', 'scan', 'text', 'screenshot', 'read'],
    shortcut: 'G Z',
    aliases: ['G 3 O'],
    accepts: ['image'],
    component: lazy(() => import('./tools/ocr/OcrTool')),
  },
  {
    id: 'forms',
    path: '/forms',
    title: 'PDF form fill',
    blurb: 'Fill AcroForm fields offline, then download.',
    category: 'Document',
    shortcut: 'G 3 F',
    keywords: ['form', 'acroform', 'fill', 'pdf', 'fields'],
    accepts: ['pdf'],
    component: lazy(() => import('./tools/forms/FormsTool')),
  },
  {
    id: 'json',
    path: '/json',
    title: 'JSON formatter',
    blurb: 'Format, validate, and minify with exact error lines.',
    category: 'Developer',
    keywords: ['json', 'format', 'validate', 'minify', 'pretty', 'parse', 'lint', 'escape'],
    shortcut: 'G J',
    aliases: ['G 6 J'],
    accepts: ['text'],
    component: lazy(() => import('./tools/json/JsonTool')),
  },
  {
    id: 'diff',
    path: '/diff',
    title: 'Text diff',
    blurb: 'Line-by-line compare, with optional JSON pretty-print.',
    category: 'Developer',
    keywords: ['diff', 'compare', 'patch', 'unified', 'text', 'json'],
    shortcut: 'G X',
    aliases: ['G 6 T'],
    accepts: ['text'],
    component: lazy(() => import('./tools/diff/DiffTool')),
  },
  {
    id: 'password',
    path: '/password',
    title: 'Password generator',
    blurb: 'Secure passwords, API tokens, and PINs with strength scoring.',
    category: 'Developer',
    keywords: ['password', 'token', 'secret', 'uuid', 'hex', 'entropy', 'secure', 'random', 'pin'],
    shortcut: 'G S',
    aliases: ['G 6 P'],
    component: lazy(() => import('./tools/password/PasswordTool')),
  },
  {
    id: 'qr',
    path: '/qr',
    title: 'QR code',
    blurb: 'Generate or scan links, Wi-Fi, email, or SMS as QR codes.',
    category: 'Developer',
    keywords: ['qr', 'qrcode', 'wifi', 'link', 'scan', 'svg', 'barcode', 'camera'],
    shortcut: 'G Q',
    aliases: ['G 6 Q'],
    accepts: ['image', 'text'],
    component: lazy(() => import('./tools/qr/QrTool')),
  },
  {
    id: 'encode',
    path: '/encode',
    title: 'Encode',
    blurb: 'Base64, URL, JWT inspect, and SHA hashes. Local only.',
    category: 'Developer',
    keywords: ['base64', 'url', 'jwt', 'sha', 'hash', 'encode', 'decode', 'token'],
    shortcut: 'G B',
    aliases: ['G 6 E'],
    accepts: ['text'],
    component: lazy(() => import('./tools/encode/EncodeTool')),
  },
  {
    id: 'text',
    path: '/text',
    title: 'Text bench',
    blurb: 'Case, slugs, word count, CSV ↔ JSON, and dummy copy.',
    category: 'Developer',
    keywords: ['case', 'slug', 'word count', 'csv', 'json', 'lorem', 'dummy'],
    shortcut: 'G L',
    aliases: ['G 6 B'],
    accepts: ['text'],
    component: lazy(() => import('./tools/text/TextTool')),
  },
  {
    id: 'regex',
    path: '/regex',
    title: 'Regex tester',
    blurb: 'Match, groups, and replace with this browser’s RegExp.',
    category: 'Developer',
    keywords: ['regex', 'regexp', 'match', 'replace', 'groups', 'pattern'],
    shortcut: 'G Y',
    aliases: ['G 6 R'],
    accepts: ['text'],
    component: lazy(() => import('./tools/regex/RegexTool')),
  },
  {
    id: 'gradient',
    path: '/gradient',
    title: 'Gradient builder',
    blurb: 'Linear, radial, conic, and mesh gradients as CSS or SVG.',
    category: 'Design',
    keywords: ['gradient', 'css', 'svg', 'linear', 'radial', 'conic', 'mesh', 'color', 'background'],
    shortcut: 'G D',
    aliases: ['G 7 G'],
    component: lazy(() => import('./tools/gradient/GradientTool')),
  },
  {
    id: 'tailwind',
    path: '/tailwind',
    title: 'Tailwind theme builder',
    blurb: 'OKLCH color scales and tokens as Tailwind v4 @theme blocks.',
    category: 'Design',
    keywords: ['tailwind', 'theme', 'oklch', 'palette', 'scale', 'tokens', 'css', 'v4', 'design system'],
    shortcut: 'G T',
    aliases: ['G 7 T'],
    component: lazy(() => import('./tools/tailwind/TailwindTool')),
  },
  {
    id: 'contrast',
    path: '/contrast',
    title: 'Contrast checker',
    blurb: 'WCAG contrast with eyedropper or a sampled screenshot.',
    category: 'Design',
    keywords: ['contrast', 'wcag', 'aa', 'aaa', 'accessibility', 'eyedropper', 'color'],
    shortcut: 'G K',
    aliases: ['G 7 C'],
    accepts: ['image'],
    component: lazy(() => import('./tools/contrast/ContrastTool')),
  },
  {
    id: 'picker',
    path: '/picker',
    title: 'Color picker',
    blurb: 'Sample a pixel. Copy hex, RGB, HSL, or OKLCH.',
    category: 'Design',
    shortcut: 'G 7 P',
    keywords: ['color', 'picker', 'eyedropper', 'hex', 'oklch', 'hsl', 'sample'],
    accepts: ['image'],
    component: lazy(() => import('./tools/picker/PickerTool')),
  },
  {
    id: 'shrink',
    path: '/shrink',
    title: 'PDF shrink',
    blurb: 'Re-render a scan or export to land under an upload limit.',
    category: 'Document',
    shortcut: 'G 3 D',
    keywords: ['pdf', 'compress', 'shrink', 'smaller', 'size', 'scan', 'upload', 'limit', 'mb', 'reduce'],
    accepts: ['pdf'],
    component: lazy(() => import('./tools/shrink/ShrinkTool')),
  },
  {
    id: 'mdtable',
    path: '/mdtable',
    title: 'Markdown table',
    blurb: 'Edit tables in a grid, not by counting pipes.',
    category: 'Document',
    shortcut: 'G 3 T',
    keywords: ['markdown', 'table', 'pipe', 'grid', 'md', 'readme', 'align'],
    accepts: ['text'],
    component: lazy(() => import('./tools/mdtable/MdTableTool')),
  },
  {
    id: 'invoice',
    path: '/invoice',
    title: 'Invoice',
    blurb: 'Line items and tax to a clean PDF. Draft stays local.',
    category: 'Document',
    shortcut: 'G 3 N',
    keywords: ['invoice', 'bill', 'receipt', 'gst', 'tax', 'freelance', 'pdf', 'quote'],
    component: lazy(() => import('./tools/invoice/InvoiceTool')),
  },
  {
    id: 'table',
    path: '/table',
    title: 'Data table',
    blurb: 'Open CSV, JSON, or .xlsx. Sort, clean, and export.',
    category: 'Data',
    shortcut: 'G 4 D',
    keywords: ['csv', 'tsv', 'excel', 'xlsx', 'spreadsheet', 'table', 'sort', 'filter', 'dedupe', 'clean', 'data'],
    accepts: ['text'],
    component: lazy(() => import('./tools/table/TableTool')),
  },
  {
    id: 'chart',
    path: '/chart',
    title: 'Chart maker',
    blurb: 'CSV to bar, line, area, scatter, or pie — as SVG or PNG.',
    category: 'Data',
    shortcut: 'G 4 C',
    keywords: ['chart', 'graph', 'plot', 'bar', 'line', 'pie', 'donut', 'scatter', 'visualise', 'csv', 'svg'],
    accepts: ['text'],
    component: lazy(() => import('./tools/chart/ChartTool')),
  },
  {
    id: 'media',
    path: '/media',
    title: 'Video & audio trim',
    blurb: 'Cut a clip, shrink it for upload, or pull the audio out.',
    category: 'Media',
    shortcut: 'G 5 V',
    keywords: ['video', 'audio', 'trim', 'cut', 'clip', 'compress', 'mp4', 'webm', 'extract', 'mute', 'shrink'],
    component: lazy(() => import('./tools/media/MediaTool')),
  },
  {
    id: 'record',
    path: '/record',
    title: 'Screen & camera recorder',
    blurb: 'Record the screen, camera, or mic and save the file.',
    category: 'Media',
    shortcut: 'G 5 S',
    keywords: ['record', 'screen', 'capture', 'webcam', 'camera', 'microphone', 'demo', 'video', 'voice'],
    component: lazy(() => import('./tools/record/RecordTool')),
  },
  {
    id: 'checksum',
    path: '/checksum',
    title: 'Checksum',
    blurb: 'SHA and CRC digests for any file, with match checking.',
    category: 'Developer',
    shortcut: 'G 6 C',
    keywords: ['hash', 'checksum', 'sha256', 'sha1', 'sha512', 'crc32', 'verify', 'digest', 'fingerprint', 'integrity'],
    component: lazy(() => import('./tools/checksum/ChecksumTool')),
  },
  {
    id: 'config',
    path: '/config',
    title: 'JSON · YAML · TOML',
    blurb: 'Convert between the three config formats.',
    category: 'Developer',
    shortcut: 'G 6 Y',
    keywords: ['yaml', 'yml', 'toml', 'json', 'convert', 'config', 'settings', 'front matter'],
    accepts: ['text'],
    component: lazy(() => import('./tools/config/ConfigTool')),
  },
  {
    id: 'cron',
    path: '/cron',
    title: 'Cron builder',
    blurb: 'Read a schedule in English and preview the next runs.',
    category: 'Developer',
    shortcut: 'G 6 O',
    keywords: ['cron', 'crontab', 'schedule', 'job', 'timer', 'expression', 'quartz'],
    accepts: ['text'],
    component: lazy(() => import('./tools/cron/CronTool')),
  },
  {
    id: 'base',
    path: '/base',
    title: 'Number base',
    blurb: 'Binary, octal, hex, and bitwise with a bit inspector.',
    category: 'Developer',
    shortcut: 'G 6 N',
    keywords: ['binary', 'hex', 'octal', 'decimal', 'bitwise', 'bit', 'mask', 'shift', 'two complement', 'radix'],
    accepts: ['text'],
    component: lazy(() => import('./tools/base/BaseTool')),
  },
  {
    id: 'diagram',
    path: '/diagram',
    title: 'Diagram',
    blurb: 'Mermaid flowcharts and sequences as SVG or PNG.',
    category: 'Design',
    shortcut: 'G 7 D',
    keywords: ['mermaid', 'diagram', 'flowchart', 'sequence', 'gantt', 'graph', 'architecture', 'svg'],
    accepts: ['text'],
    component: lazy(() => import('./tools/diagram/DiagramTool')),
  },
  {
    id: 'vision',
    path: '/vision',
    title: 'Colour vision',
    blurb: 'Simulate colour blindness on a palette or screenshot.',
    category: 'Design',
    shortcut: 'G 7 V',
    keywords: [
      'colour blind',
      'color blind',
      'deuteranopia',
      'protanopia',
      'tritanopia',
      'accessibility',
      'a11y',
      'palette',
      'simulate',
    ],
    accepts: ['image'],
    component: lazy(() => import('./tools/vision/VisionTool')),
  },
  {
    id: 'meet',
    path: '/meet',
    title: 'Meeting planner',
    blurb: 'Line up working hours across zones and find the overlap.',
    category: 'Daily',
    shortcut: 'G 1 M',
    keywords: ['meeting', 'timezone', 'time zone', 'overlap', 'schedule', 'world clock', 'standup', 'call'],
    component: lazy(() => import('./tools/meet/MeetTool')),
  },
  {
    id: 'age',
    path: '/age',
    title: 'Age & date difference',
    blurb: 'Exact years, months, and days between two dates.',
    category: 'Daily',
    shortcut: 'G 1 A',
    keywords: ['age', 'date', 'difference', 'birthday', 'anniversary', 'days between', 'how old'],
    accepts: ['text'],
    component: lazy(() => import('./tools/age/AgeTool')),
  },
  {
    id: 'deadline',
    path: '/deadline',
    title: 'Deadline calculator',
    blurb: 'Add working days, skipping weekends and your holidays.',
    category: 'Daily',
    shortcut: 'G 1 D',
    keywords: ['deadline', 'working days', 'business days', 'sla', 'due date', 'holidays', 'turnaround'],
    accepts: ['text'],
    component: lazy(() => import('./tools/deadline/DeadlineTool')),
  },
  {
    id: 'timers',
    path: '/timers',
    title: 'Timers',
    blurb: 'Countdown, stopwatch, and Pomodoro in one place.',
    category: 'Daily',
    shortcut: 'G 1 T',
    keywords: ['timer', 'countdown', 'stopwatch', 'pomodoro', 'alarm', 'focus', 'lap'],
    component: lazy(() => import('./tools/timers/TimersTool')),
  },
  {
    id: 'random',
    path: '/random',
    title: 'Random picker',
    blurb: 'Wheel spinner, dice, coin flip, and fair team splitting.',
    category: 'Daily',
    shortcut: 'G 1 R',
    keywords: ['random', 'wheel', 'spinner', 'dice', 'coin', 'teams', 'raffle', 'shuffle', 'pick'],
    accepts: ['text'],
    component: lazy(() => import('./tools/random/RandomTool')),
  },
  {
    id: 'numwords',
    path: '/numwords',
    title: 'Number to words',
    blurb: 'Spell out amounts in lakh, crore, or millions.',
    category: 'Daily',
    shortcut: 'G 1 N',
    keywords: ['number to words', 'amount in words', 'cheque', 'lakh', 'crore', 'rupees', 'spell', 'invoice'],
    accepts: ['text'],
    component: lazy(() => import('./tools/numwords/NumWordsTool')),
  },
  {
    id: 'health',
    path: '/health',
    title: 'Health calculators',
    blurb: 'BMI, resting energy, daily calories, and macros.',
    category: 'Daily',
    shortcut: 'G 1 H',
    keywords: ['bmi', 'bmr', 'tdee', 'calories', 'macros', 'protein', 'weight', 'fitness', 'diet'],
    component: lazy(() => import('./tools/health/HealthTool')),
  },
  {
    id: 'trip',
    path: '/trip',
    title: 'Trip cost',
    blurb: 'Fuel, tolls, and per-head split for a journey.',
    category: 'Daily',
    shortcut: 'G 1 I',
    keywords: ['fuel', 'petrol', 'mileage', 'trip', 'travel', 'split', 'road trip', 'toll', 'cost'],
    component: lazy(() => import('./tools/trip/TripTool')),
  },
  {
    id: 'carousel',
    path: '/carousel',
    title: 'Carousel splitter',
    blurb: 'Slice a wide image into numbered Instagram panels.',
    category: 'Image',
    shortcut: 'G 2 A',
    keywords: ['carousel', 'instagram', 'slice', 'split', 'panels', 'swipe', 'linkedin', 'panorama'],
    accepts: ['image'],
    component: lazy(() => import('./tools/carousel/CarouselTool')),
  },
  {
    id: 'meme',
    path: '/meme',
    title: 'Meme generator',
    blurb: 'Top and bottom text with the right stroke and font.',
    category: 'Image',
    shortcut: 'G 2 G',
    keywords: ['meme', 'caption', 'impact', 'top text', 'bottom text', 'funny'],
    accepts: ['image'],
    component: lazy(() => import('./tools/meme/MemeTool')),
  },
  {
    id: 'ascii',
    path: '/ascii',
    title: 'ASCII from image',
    blurb: 'Turn a photo into text art at any density.',
    category: 'Image',
    shortcut: 'G 2 O',
    keywords: ['ascii', 'art', 'text art', 'image to text', 'terminal', 'retro'],
    accepts: ['image'],
    component: lazy(() => import('./tools/ascii/AsciiTool')),
  },
  {
    id: 'noise',
    path: '/noise',
    title: 'Noise generator',
    blurb: 'White, pink, and brown noise with a sleep timer.',
    category: 'Media',
    shortcut: 'G 5 N',
    keywords: ['noise', 'white noise', 'pink', 'brown', 'sleep', 'focus', 'ambient', 'concentration'],
    component: lazy(() => import('./tools/noise/NoiseTool')),
  },
  {
    id: 'soundmeter',
    path: '/soundmeter',
    title: 'Sound meter',
    blurb: 'Live decibel reading from the microphone.',
    category: 'Media',
    shortcut: 'G 5 M',
    keywords: ['decibel', 'db', 'sound', 'loudness', 'noise level', 'spl', 'microphone', 'meter'],
    component: lazy(() => import('./tools/soundmeter/SoundMeterTool')),
  },
  {
    id: 'styler',
    path: '/styler',
    title: 'Unicode text styler',
    blurb: 'Bold and italic for bios that strip formatting.',
    category: 'Writing',
    shortcut: 'G 8 U',
    keywords: ['unicode', 'bold', 'italic', 'fancy text', 'bio', 'font', 'style', 'instagram', 'twitter'],
    accepts: ['text'],
    component: lazy(() => import('./tools/styler/StylerTool')),
  },
  {
    id: 'emoji',
    path: '/emoji',
    title: 'Emoji search',
    blurb: 'Find emoji and kaomoji by meaning, copy instantly.',
    category: 'Writing',
    shortcut: 'G 8 E',
    keywords: ['emoji', 'emoticon', 'kaomoji', 'smiley', 'symbol', 'search', 'copy'],
    component: lazy(() => import('./tools/emoji/EmojiTool')),
  },
  {
    id: 'counter',
    path: '/counter',
    title: 'Platform counter',
    blurb: 'Character counts against X, LinkedIn, and SEO limits.',
    category: 'Writing',
    shortcut: 'G 8 P',
    keywords: ['character count', 'word count', 'limit', 'twitter', 'x', 'linkedin', 'meta description', 'seo', 'sms'],
    accepts: ['text'],
    component: lazy(() => import('./tools/counter/CounterTool')),
  },
  {
    id: 'readability',
    path: '/readability',
    title: 'Readability',
    blurb: 'Reading time, Flesch score, and the sentences to fix.',
    category: 'Writing',
    shortcut: 'G 8 R',
    keywords: ['readability', 'flesch', 'reading time', 'grade level', 'passive voice', 'editing', 'clarity'],
    accepts: ['text'],
    component: lazy(() => import('./tools/readability/ReadabilityTool')),
  },
  {
    id: 'boxdraw',
    path: '/boxdraw',
    title: 'Box drawing',
    blurb: 'ASCII tables, boxes, and trees for READMEs.',
    category: 'Writing',
    shortcut: 'G 8 B',
    keywords: ['ascii table', 'box drawing', 'tree', 'readme', 'unicode', 'terminal', 'comment', 'diagram'],
    accepts: ['text'],
    component: lazy(() => import('./tools/boxdraw/BoxDrawTool')),
  },
  {
    id: 'settings',
    path: '/settings',
    title: 'Data & settings',
    blurb: 'Back up everything, restore it, and see what you use most.',
    category: 'Notes',
    shortcut: 'G 9 D',
    keywords: ['backup', 'restore', 'export', 'import', 'settings', 'data', 'storage', 'clear', 'usage'],
    component: lazy(() => import('./tools/settings/SettingsTool')),
  },
  {
    id: 'pipelines',
    path: '/pipelines',
    title: 'Pipelines',
    blurb: 'Save a sequence of tools and rerun it on demand.',
    category: 'Notes',
    shortcut: 'G 9 P',
    keywords: ['pipeline', 'workflow', 'chain', 'recipe', 'automation', 'steps', 'batch', 'repeat'],
    component: lazy(() => import('./tools/pipelines/PipelinesTool')),
  },
  {
    id: 'notes',
    path: '/notes',
    title: 'Local notes',
    blurb: 'A scratchpad that stays in this browser.',
    category: 'Notes',
    keywords: ['note', 'scratch', 'localstorage', 'indexeddb', 'memo'],
    shortcut: 'G N',
    aliases: ['G 9 L'],
    accepts: ['text'],
    component: lazy(() => import('./tools/notes/NotesTool')),
  },
]

export function searchTools(query: string): ToolMeta[] {
  const q = query.trim().toLowerCase()
  if (!q) return tools
  return tools.filter((tool) => {
    const hay = [tool.title, tool.blurb, tool.category, ...tool.keywords]
      .join(' ')
      .toLowerCase()
    return hay.includes(q)
  })
}

export function getTool(id: string): ToolMeta | undefined {
  return tools.find((tool) => tool.id === id)
}
